#include <stdio.h>

//请根据主程序流程，补全此函数
//冰雹产生并输出函数
//注意：输出每个冰雹数时，请按5位对齐输出
void hailstone(int n) 
{
    printf("Hailstone generated by %d:\n",n);
    /**********  Begin **********/
           int i = 1;
    if( n != 1){

    printf("%5d",n);
    }
    while(n > 1){
    if(n % 2 == 0 && n / 2 != 1){
        n = n / 2;
        i ++;
        if(i % 6 == 0){
            printf("%5d\n",n);
        }
        else{
            printf("%5d",n);
        }
    }
    else if(n %2 == 1 && n != 1){
        n = 3* n + 1;
        i++;
        if(i % 6 == 0){
            printf("%5d\n",n);
        }
        else{
            printf("%5d",n);
        }
    
    }
    else if(n % 2 == 1 && n == 1){
        i++;
    }
    else if(n % 2 == 0 && n/2 == 1){
        i ++;
        n = n/2;

    }
    }



    /**********  End  **********/
    printf("%5d\n",n);
	printf("Number of hailstone generated:%d",i);
}
